server:
  port: 4003

spring:
  cloud:
    gateway:
      routes:
      ### REST Client -> http://localhost:4003/api/patients
      ### API GATEWAY -> http://patient-service:4000/patients
        - id: patient-route-api-prefix
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1

      ### REST Client -> http://localhost:4003/patients
      ### API GATEWAY -> http://patient-service:4000/patients
        - id: patient-route-direct
          uri: http://patient-service:4000
          predicates:
            - Path=/patients/**


      ### REST-CLIENT -> http://localhost:4003/api-docs/patients
      ### API GATEWAY -> `http://patient-service:4000/v3/api-docs`
        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients, /v3/api-docs


