POST http://localhost:4000/patients

Content-Type: application/json

{
    "name": "Urvaja Magarde",
    "email": "urvaja@sap.com",
    "address": "123 main street",
    "dateOfBirth": "2010-09-28",
    "registeredDate": "2026-04-07"
}