POST http://localhost:4000/patients

Content-Type: application/json

{
    "name": "Swapnaja Magarde",
    "email": "swapnaja@sap.com",
    "address": "123 main street",
    "dateOfBirth": "2004-06-09",
    "registeredDate": "2026-03-30"
}